/*
 * This file is part of HiKoB Openlab.
 *
 * HiKoB Openlab is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, version 3.
 *
 * HiKoB Openlab is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with HiKoB Openlab. If not, see
 * <http://www.gnu.org/licenses/>.
 *
 * Copyright (C) 2011,2012 HiKoB.
 */

/** \example example_lsm303dlhc_polling.c
 * This file is an example of the use of LSM303DLHC accelerometer+magnetometer
 *      in accelerometer mode only, reading data on interrupt generated by the sensor
 * sensor measure (polling).
 * \date Sep 27, 2012
 * \author Christophe Braillon <christophe.braillon.at.hikob.com>
 */

#include <stdint.h>
#include <math.h>
#include "platform.h"
#include "drivers.h"
#include "printf.h"
#include "lsm303dlhc.h"

static void app_task(void *);
static xSemaphoreHandle sync;

static void accelero_data(handler_arg_t arg)
{
    signed portBASE_TYPE pxHigherPriorityTaskWoken;

    // Signal the application that a sample is available
    xSemaphoreGiveFromISR(sync, &pxHigherPriorityTaskWoken);
}

int main()
{
    // Initialize the platform
    platform_init();

    // Create synchronization mutex
    sync = xSemaphoreCreateCounting(1, 0);

    // Create a task for the application
    xTaskCreate(app_task, (const signed char * const) "lsm303", configMINIMAL_STACK_SIZE, NULL, 1, NULL);

    // Run
    platform_run();
    return 0;
}

#define ACC_RES (1e-3)  // The resolution is 1mg for the +/-2g scale

static void app_task(void *param)
{
    int16_t a[3];
    int16_t cpt = 0;
    uint32_t t;

    printf("# Testing LSM303DLHC\n");

    printf("# Initializing LSM303DLHC...\n");
    lsm303dlhc_powerdown();

    printf("# Setting LSM303DLHC accelerometer\n");
    lsm303dlhc_acc_config(LSM303DLHC_ACC_RATE_100HZ, LSM303DLHC_ACC_SCALE_2G, LSM303DLHC_ACC_UPDATE_ON_READ);

    printf("# Setup LSM303DLHC data handler\n");
    lsm303dlhc_acc_set_drdy_int1(accelero_data, NULL);

    // Start a dummy reading to boostrap the interrupts
    lsm303dlhc_read_acc(a);

    t = soft_timer_time();

    while (1)
    {
        // Wait for an interrupt to come
        xSemaphoreTake(sync, portMAX_DELAY);

        // Read the values
        while(lsm303dlhc_acc_get_drdy_int1_pin_value())
        {
            lsm303dlhc_read_acc(a);
            cpt++;
        }

        if(cpt >= 100)
        {
            cpt = 0;
            printf("dt: %d\n", soft_timer_ticks_to_ms(soft_timer_time()-t));
            t = soft_timer_time();
        }
    }
}
